# Generated by Django 5.2.4 on 2025-07-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testimonial',
            unique_together={('professor', 'student_name')},
        ),
    ]
